- ui/editor/extensions/slash-command.tsx
<details open>
<summary> Demo </summary>
https://github.com/steven-tey/novel/assets/45892659/cd053971-0ace-4d12-8e5e-64fa1bfe13ea
</details>
In demo, I reduced the height of the `commandListContainer` to `h-56`, but reverted it to `h-auto` after I tested it. 
---
closes #6
> feat(command list): scrolling to the item when navigating with keyboard

- ui/editor/extensions/index.tsx
Prevent spellcheck from leaving red underlines in code.
*Turning this...*
*Into this!*
Spellcheck still works as expected in normal text blocks:
> fix: prevent browser spellcheck in inline-code/code blocks

- app/api/generate/route.ts
The current implementation is to cut the content from the top and stop after 5000 characters.
If the article/document is longer than 5000 characters, the content will always be the same, and the Chat completion function will be stuck repeating the same answers (wrong answers in this case)
**Fix:** 
- To cut the content from the bottom to make sure we feed the Chat completion function the latest text.
> fix(api): Slice content from the end to prioritize later characters

- app/api/generate/route.ts
PR Description: Resolve issue #86 by enhancing error handling for the OpenAI API key. 
When the API key is not set, it now displays a clear message in the toast box indicating that no API key is set. 
Additionally, if an invalid API key is provided, it shows an "Unauthorized" error message in the toast box, improving user feedback and error resolution.
> added no OPENAI key set support

- ui/editor/components/link-selector.tsx
If you select text and click the checkmark icon to add a link to a document without actually inserting a link, an empty link is created. I have resolved this issue.
Bug:
Here's what has been fixed:
Thank you!
> Fixed empty "link" input string

- packages/core/src/ui/editor/extensions/drag-and-drop.tsx
Fix for issue #146 
Have disabled `drag-handle` element for `ul` and `ol`.
The `drag-handle` for list items should now display properly: 
https://github.com/steven-tey/novel/assets/28751435/23401728-a441-47f6-a864-d9a83a792adb
> fix: draggable icon is misplaced in ordered and unordered lists (#146)

- README.md
Existing license link in the `README.md` file is incorrect and includes the `.md` extension. This is not needed and results in a broken link. To resolve, I've opened this PR and have [updated the link](https://github.com/steven-tey/novel/commit/62b70c189b74f4e2c4a6c9245c71d81334f7893a) so that it routes to the proper location. 
**Reference:**
- Existing Link: [here](https://github.com/steven-tey/novel/blob/main/LICENSE.md)
- Updated Link: [here](https://github.com/steven-tey/novel/blob/main/LICENSE)
> [Fix] - Correct License Link in README.md

- apps/web/styles/prosemirror.css
- packages/headless/src/extensions/drag-and-drop.tsx
closes #275
- Fix behavior of image not move when moving the dot handle
- remove **border-radius: 0.2rem;** from class **.ProseMirror-selectednode** because it overrides the default border radius of image after first move.
The solution is similar of made some lines below on another behavior
https://github.com/steven-tey/novel/blob/74dc2c8c28a94fcbb383c768b0e6c13b8dcdc947/packages/headless/src/extensions/drag-and-drop.tsx#L81
Tiptap use the same approach
https://github.com/ueberdosis/tiptap/blob/6ab708b1a2138adafe07535363fdc53ac7a8f208/demos/src/Experiments/GlobalDragHandle/Vue/DragHandle.js#L121-L125
https://github.com/steven-tey/novel/assets/13812512/fd26be66-e128-4e69-915d-6c078f27d182
> fix: image move when dragged

- packages/headless/src/extensions/updated-image.ts
**Link to the bug:** [Issue 309](https://github.com/steven-tey/novel/issues/309)
After an image was changed by react-moveable, the type was overridden by "updated-image" which caused the ImageResizer to unrecognize the ContentType, which should be "image." 
Before resize: 
https://github.com/steven-tey/novel/assets/49728880/4ed7c476-7c0c-46b6-ad6d-d2eaee61e3ac
After resize: 
ImageResizer only handles the type "image"
If there is a particular reason to have "updated-image" type feel free to discard this otherwise, this is a tiny fix 😏
> fix: rename updated image type

- apps/web/components/tailwind/selectors/node-selector.tsx
In some cases when select a new node on node selector, it remains with previous selection
https://github.com/steven-tey/novel/assets/13812512/0a297629-c2b1-4fec-ae55-cb51ea59bd93
I added `.clearNodes() `to all command chains on select nodes, this way all nodes become a paragraph, before to be applied new node, removing completely old node references.
https://github.com/steven-tey/novel/assets/13812512/b82fd967-8057-47e9-94b2-3cc5c1dcb393
> feat: clear nodes on node selector

- packages/headless/src/extensions/drag-and-drop.tsx
After drag and drop an element drag handler element still rendered on original position 
https://github.com/steven-tey/novel/assets/13812512/f2eb343f-aee8-4efc-8f5e-629e7285bf87
hide drag and drop element on drop event
https://github.com/steven-tey/novel/assets/13812512/5c8a8215-e90f-4e5b-a0f1-b56203e89857
> fix: remove drag-handle on drop

- packages/headless/src/extensions/slash-command.tsx
closes #324 
dont render slash command on nodes of type codeBlock
https://github.com/steven-tey/novel/assets/13812512/592fbc5b-14d7-4ae0-b400-7995bf9b981b
> fix: dont trigger slash-command on codeBlock nodes

- packages/headless/src/components/editor-bubble.tsx
**Changes:**
- Only show Bubble Menu if editor can be editable
closes #346
> fix: not show bubble menu if editor cannot be editable

- apps/docs/guides/tailwind/extensions.mdx
Fixed the docs at https://novel.sh/docs/guides/tailwind/extensions as the code is broken.
1. Fixed exports (`tiptapImage` -> `TiptapImage`)
2. Removed unused `slashCommand` import
> fix(docs): tailwind extensions guide

- apps/web/components/tailwind/advanced-editor.tsx
- apps/web/components/tailwind/extensions.ts
- apps/web/package.json
- apps/web/styles/globals.css
- packages/headless/package.json
- packages/headless/src/extensions/index.ts
- pnpm-lock.yaml
I have added the support for code syntax highlighting in code-blocks.
Following changes were included:
Added `@tiptap/extension-code-block-lowlight ` to headless package. No styling added here to keep it headless.
Enhanced the web application and added css styles to globals.css. Configured the lowlight using highlight languages in `extensions.ts`. 
`const lowlight = createLowlight(common);
lowlight.register("html", html);
lowlight.register("css", css);
lowlight.register("js", js);
lowlight.register("ts", ts);`
`const codeBlockLowlight = CodeBlockLowlight.configure({
lowlight,
});`
> feat: Added support for code blocks syntax highlighting

- apps/web/components/tailwind/advanced-editor.tsx
- apps/web/components/tailwind/extensions.ts
- apps/web/components/tailwind/slash-command.tsx
- apps/web/styles/prosemirror.css
- packages/headless/package.json
- packages/headless/src/extensions/index.ts
Old PR generated merge conflicts with recent main merges. https://github.com/steven-tey/novel/pull/383
Feat:
Added basic Youtube Embed Feature + Word Counter
Addressing Issue: https://github.com/steven-tey/novel/issues/359
Demo:
https://github.com/steven-tey/novel/assets/122026167/eee1c129-ad6e-434a-b60c-f692b2609f22
> feat: Basic YT Embeds + CharCount Support

- apps/web/components/tailwind/advanced-editor.tsx
This is a fix for Bug: https://github.com/steven-tey/novel/issues/394
Bug and Fix:
https://github.com/steven-tey/novel/assets/122026167/ffa60862-7d45-4d2e-8277-2255a5639d14
> fix: codeblock-lowlight doesn't render in html output

- packages/headless/src/extensions/slash-command.tsx
The renderItems function can accept an optional parameter, a react ref to an element in DOM, to which slash commands are appended.
> Feat: Specify Element to which Slash Commands are Added

- apps/docs/guides/tailwind/setup.mdx
- apps/web/styles/prosemirror.css
This is fix for : https://github.com/steven-tey/novel/issues/398
plus highlight bold text color fix.
Bug Vid:
https://github.com/steven-tey/novel/assets/122026167/a4aa72f1-5481-4d5d-a7cf-67ccd9c83f1d
> fix : bold text color + bold highlight color

- apps/docs/guides/tailwind/slash-command.mdx
This pull request fixes an issue where `suggestionItems` were not wrapped with the `<EditorCommandList>` component, which is necessary for proper functionality.
- Wrapped `suggestionItems` with `<EditorCommandList>`.
The `suggestionItems` need to be wrapped with `<EditorCommandList>` to ensure they function correctly. Without this wrapper, the suggestions may not display or behave as intended.
> Fix: Wrap suggestionItems with <EditorCommandList>

- apps/web/components/tailwind/selectors/color-selector.tsx
- apps/web/components/tailwind/selectors/link-selector.tsx
- examples/novel-tailwind/src/components/editor/selectors/color-selector.tsx
- examples/novel-tailwind/src/components/editor/selectors/link-selector.tsx
> bug: Usage of `editor.chain().focus()` removes focus from tippy popover  Fixes #412

- apps/web/components/tailwind/extensions.ts
This PR will allow editor to set initial content in `HTML` or `markdown` format as a string.
> feat: Added markdownExtension to allow html and markdown string as initial content
